name: Build and Package
on:
  # manual deployment to Visual Studio Code Marketplace
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Install vsce
      run: npm i -g vsce

    - name: Package
      run: vsce package

    - name: Artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        path: "*.vsix"

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
    - uses: actions/download-artifact@v3
    - name: Publish
      run: vsce publish -p ${{ secrets.VSCE_PAT }}
