name: Publish to marketplace
on:
  # manual deployment to Visual Studio Code Marketplace
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Install vsce
      run: npm i -g vsce

    - name: Package
      run: vsce package

    - name: Artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        path: "*.vsix"

    - name: Publish
      if: success()
      run: vsce publish -p ${{ secrets.VSCE_PAT }}
